### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by fulltimemike** [AleoHQ/snarkVM#1126] opened 2022-09-30 19:01 UTC
## 🐛 Bug Report

GET requests in the [`routes`](https://github.com/AleoHQ/snarkVM/blob/testnet3/rest/src/routes.rs) file [should not include bodies](https://developer.mozilla.org/en-US/docs/Web/HTTP/Methods/GET). Some http request libraries (like fetch.ts) are unable to create GET requests with bodies and error out before every submitting to the snarkVM endpoints.

## Steps to Reproduce

The error is found in all GET requests in [`routes`](https://github.com/AleoHQ/snarkVM/blob/testnet3/rest/src/routes.rs) with a body json included in the warp filter.

## Expected Behavior

There are two potential fixes. Either the methods could be converted to POST requests, or the body content (view_key) could be made a query parameter. Making the view_key a query parameter may have negative security implications.

## Your Environment

- commit e2ed1c8cb9d3f4692be4dd1f7b5bbb8f4c41ccfa
- rustc 1.65.0-nightly
- mac OS

**Comment by ljedrz** [comment] 2022-09-30 20:25
Closing as a duplicate of https://github.com/AleoHQ/snarkOS/issues/2010.

**Closed as completed by ljedrz** 2022-09-30 20:25 UTC
Labels: bug, duplicate
